#!/bin/bash

XCODE_USER_TEMPLATES_DIR=$HOME/Library/Developer/Xcode/Templates/File\ Templates
MVC_TEMPLATES_DIR=MVC
DS_TEMPLATES_DIR=DataSource

mkdir -p "$XCODE_USER_TEMPLATES_DIR"

echo "Installing MVC templates"
rm -fR "$XCODE_USER_TEMPLATES_DIR/$MVC_TEMPLATES_DIR"
cp -R "$MVC_TEMPLATES_DIR" "$XCODE_USER_TEMPLATES_DIR"

echo "Installing DataSource templates"
rm -fR "$XCODE_USER_TEMPLATES_DIR/$DS_TEMPLATES_DIR"
cp -R "$DS_TEMPLATES_DIR" "$XCODE_USER_TEMPLATES_DIR"